### ISSUE TITLE
Implement Concrete syntax (CST) support

### ISSUE THREAD

**Issue by KFlash** [escaya/escaya#12]
There will not be a complete support for concrete syntax, but some additional info has been and will be added. See the AST specs for more details.

Additional info has been added to the AST while parsing with module goal. It can be seen in the online demo. 

I also consider to handle comments, whitespace and lexical scoping the same way.

This is an mayor improvement over Estree and the Babel parser AST

**Comment by KFlash** [comment]
A new option - `cst: boolean` have been added for additional CST info that doesn't exist in the specs.

**Comment by KFlash** [comment]
Additional CST info will be continuously added while I'm developing the [Escaya code generator](https://github.com/escaya).

The additional CST information will be behind a optional `cst` flag.

**Comment by KFlash** [comment]
Additional CST will be continuously added while I'm developing [Escaya code generator](info https://github.com/escaya/escaya-codegen)

The additional CST will be hidden behind a optional `cst` flag.

**Comment by KFlash** [comment]
Closing as this has been solved.

**Comment by KFlash** [comment]
A [concrete syntax example[(https://escaya.github.io/escaya/?code=a%20%3D%20b%3B%0A&method=parse&range=undefined&loc=false&next=false&cst=true&module=false&raw=undefined&jsx=undefined&directives=undefined&attachComment=undefined&webCompat=undefined&lexical=undefined)

**Comment by michael-ciniawsky** [comment]
Would it be possible/beneficial to group the CST props together somehow? e.g with a `meta`  key on each node

```
{
    "type": "Script",
    "webCompat": true,
    "directives": [],
    "leafs": [
        {
            "type": "ExpressionStatement",
            "expression": {
                "type": "AssignmentExpression",
                "left": {
                    "type": "IdentifierReference",
                    "name": "a",
                    "newlineBeforeNextToken": false,
                    "asi": false
                },
                "operator": "=",
                "right": {
                    "type": "IdentifierReference",
                    "name": "b",
                    "newlineBeforeNextToken": false,
                    "asi": true
                },
                "newlineBeforeNextToken": false,
                "asi": true
            },
            "newlineBeforeNextToken": true,
            "asi": true
        }
    ]
}
```

```diff
{
    "type": "Script",
    "webCompat": true,
    "directives": [],
    "leafs": [
        {
            "type": "ExpressionStatement",
            "expression": {
                "type": "AssignmentExpression",
                "left": {
                    "type": "IdentifierReference",
                    "name": "a",
+                   "meta": {
+                     "asi": true,
+                      "space": {
+                         "before": 0,
+                         "after": 1,
+                      },
+                      "newline": true,
+                    },
-                    "newlineBeforeNextToken": false,
-                    "asi": false
                },
                "operator": "=",
                "right": {
                    "type": "IdentifierReference",
                    "name": "b",
+                   "meta": {
+                     "asi": true,
+                      "space": {
+                         "before": 1,
+                         "after": 0,
+                      },
+                      "newline": true,
+                       // ...other CST props
+                    },
                },
-                "newlineBeforeNextToken": false,
-                "asi": true
            },
+           "meta": {
+                "asi": true,
+                "space": {
+                      "before": 0,
+                      "after": 0,
+                  },
+                 "newline": true,
+             },
-            "newlineBeforeNextToken": true,
-            "asi": true
        }
    ]
}
```

In my opinion this makes it cleaner to distiguish between AST and CST properties. It's also easier for (third-party) consumers to check if CST properties are present (enable via `options`)

```js
import { parseScript } from 'escaya'
import { traverse } from 'some-tree-walker'

const ast = parseScript('a = b', {
  cst: true
})

traverse(ast, {
   IdentifierReference (node, state) {
        if (node.meta) {
             // e.g 
             node.meta.space.after = 4
        }
   }
}
```

**Comment by KFlash** [comment]
I'm agree in your idea there. It's easy enough to group them. Do you want to do a PR?
I'm stuck with my code generator again.

**Comment by michael-ciniawsky** [comment]
> Do you want to do a PR?

Yep, will try :)

**Comment by KFlash** [comment]
This is things I consider to add  as additional CST info. 

Comments, spaces, absolute parenthesis wrapping. Comments will be done same way as in Acorn. I d

Newline; cr vs lf vs crlf and  EmptyStatement (useless semi colons) has medium  priority 

And someone also mentioned Unicode edge cases. Escape sequences (\uabcd vs \u{abc} vs \u{000000ab} vs \xab  vs \2), also escape sequences in idents

**Comment by michael-ciniawsky** [comment]
Yes I got it working, updating the tests right now and will open a Draft (PR) soon for further discussion :)

**Comment by KFlash** [comment]
How's the progress on this?

**Comment by KFlash** [comment]
@michael-ciniawsky Did you fix the meta property? I just found out that a 'isFloat' value has to be added as well for number literals for cases like `15..valueOf()`.  In EScodegen and other code generators they wrap it in parens if the precedence value is lower than member expr. 

With a new `float` property all this can be avoided and a `.` can be added if float.

I'm adding this to numeric literal node now, but it's belong to concrete syntax, so if you could move it under the 'meta' property?

**Comment by KFlash** [comment]
@michael-ciniawsky See this commit https://github.com/escaya/escaya/commit/d933b861ea520f6534fe27ed6ae0c0deac1da4fd 

I didn't go further with this because waiting for your PR. Somehow this additional info has to be folded into the `meta` property as well.
