### ISSUE TITLE
README says "Supports JSON" - What does this mean?

### ISSUE THREAD

**Issue by axefrog** [escaya/escaya#14]
Getting closer now to starting to use Escaya. I have just been looking for a good way to identify which part of a JSON object my cursor is currently focused on (using Monaco editor) and I remembered that Escaya mentioned support for JSON. I can't find any information detailing what kind of JSON support Escaya is referring to though.

![2020-09-04_09-26-35](https://user-images.githubusercontent.com/298883/92183132-cec5eb00-ee90-11ea-8149-8fd998a363a1.gif)

**Comment by KFlash** [comment]
Let's take EStree as an example

This production will give you issues with JSON, and there are many other examples in the ESTree specs

```js
`interface RegExpLiteral <: Literal {
  regex: {
    pattern: string;
    flags: string;
  };
}`
```

Equalent in Escaya 

```js
interface RegularExpressionLiteral <: Expression {
    type: 'RegularExpressionLiteral';
    pattern: string;
    flag: RegExpFlags;
}
```

The latter doesn't give you any JSON issues. That's why I wrote it was "friendly" :)

**Comment by axefrog** [comment]
Ah, gotcha, thanks
