### ISSUE TITLE
Unwanted EmptyStatement after any ExportDeclaration

### ISSUE THREAD

**Issue by eobodo** [escaya/escaya#20]
Any after ExportDeclaration, the parser adds an extra EmptyStatement.

Test Case:
https://escaya.github.io/escaya/?code=const%20a%20%3D%201%3B%0Aexport%20%7Ba%7D%3B&method=parse&range=undefined&loc=false&next=false&cst=false&module=true&raw=undefined&jsx=undefined&directives=undefined&attachComment=undefined&webCompat=undefined&lexical=undefined

**Comment by KFlash** [comment]
Thanx for this info. It's already been fixed.
