### ISSUE TITLE
ExportDefault Class or Function declarations without a name should be a parsed as an expression

### ISSUE THREAD

**Issue by eobodo** [escaya/escaya#21]
Any ClassExpression or FunctionExpression under the ExportDefault "declaration" property is currently parsed as a ClassDeclaration or FunctionDeclaration instead.

Test Case:
https://escaya.github.io/escaya/?code=export%20default%20class%20%7B%7D%0A%2F%2Fexport%20default%20function%20()%20%7B%7D%0A&method=parse&range=undefined&loc=false&next=false&cst=false&module=true&raw=undefined&jsx=undefined&directives=undefined&attachComment=undefined&webCompat=undefined&lexical=undefined

**Comment by KFlash** [comment]
This is correct after the specs. And if you study the AST you will notice the "declarations" property. 
Functions in your example should be treated as HoistableDeclaration.

If you want to export an FunctionExpression, you do `export default x = function y() {}`

See the section '15.2.3 Exports' in the ECMASpecs.

**Comment by eobodo** [comment]
Oh. I was toying around with a code generator of my own (to help me understand the spec better) when I ran into a small problem resolving ClassDeclarations. The AST specs says ClassDeclaration and FunctionDeclaration "name" property is a BindingIdentifier. But when it came to parsing class/function declarations inside of an ExportDefault node, I had to tweak the logic to accept these name properties as BindingIdentifiers || null. Similar to their expression counterparts.

**Comment by KFlash** [comment]
I see. The Escaya AST spec follows the ECMA specs 96%. I only "shortened" a few productions to make sure the AST consumes less bytes, and used similar names for pattern, assignment and expressions when it comes to reinterpretation too maintain performance.
If you see something odd with current AST sepcs, I'm more than happy if you know.

A WIP code gen for the Escaya AST can be found [here](https://github.com/escaya/escaya-codegen)
