### ISSUE TITLE
NamedImports (ImportSpecifier) can have a keyword or expression as a valid name if it is aliased.

### ISSUE THREAD

**Issue by eobodo** [escaya/escaya#22]
Test case:
https://escaya.github.io/escaya/?code=import%20%7B%0A%20%20class%20as%20a%2C%0A%20%20true%20as%20b%2C%0A%20%20*%20as%20c%0A%7D%20from%20'someModule.js'%3B%0A&method=parse&range=undefined&loc=false&next=false&cst=false&module=true&raw=undefined&jsx=undefined&directives=undefined&attachComment=undefined&webCompat=undefined&lexical=undefined

**Comment by KFlash** [comment]
I don't get you on this one. This is passing as it should, what's the issue?

**Comment by eobodo** [comment]
Sorry I guess you can use keywords or expressions as names within NamedImports. I've modified the test case to focus on literals and the "*" token instead. It doesn't seem to pass in both node or acorn. Also look at how the ImportSpecifier with the "*" token is parsed. It reuses the identifier from the previous ImportSpecifier.

https://escaya.github.io/escaya/?code=import%20%7B%0A%20%201%20as%20add%2C%0A%20%20*%20as%20sub%0A%7D%20from%20'someModule.js'%3B%0A&method=parse&range=undefined&loc=false&next=false&cst=false&module=true&raw=undefined&jsx=undefined&directives=undefined&attachComment=undefined&webCompat=undefined&lexical=undefined

**Comment by KFlash** [comment]
It was a slip-up with the bitwise masks. I think this is solved now. Thanks for the report!
