### ISSUE TITLE
WIP features

### ISSUE THREAD

**Issue by KFlash** [escaya/escaya#8]
* AST transformer for normal mode so any AST can be used through plugins

* Custom diagnostic messages

* Hooks

* Maybe transformers to do "linting" , typechecking etc. so no need for 3rd party scripts like Babel and Eslint. This is for **future**. Not v. 1.0

**Comment by lukeed** [comment]
Replied to your [gist](https://gist.github.com/KFlash/361a6f5a99ce1aa2a492bddca9d0fa03). Happy to move the conversation here/on the gist

**Comment by KFlash** [comment]
Ideas how and where to document the new changes? Example the API and plugin changes?

**Comment by KFlash** [comment]
Closing as this is on my TODO now
